# Generated by Django 5.1.4 on 2026-05-17 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('confirmed', 'Confirmado'), ('shipped', 'Enviado'), ('delivered', 'Entregado'), ('completed', 'Completada'), ('cancelled', 'Cancelado')], default='pending', max_length=20),
        ),
    ]
