# Generated by Django 5.1.4 on 2026-05-02 02:11

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('slug', models.SlugField(blank=True, max_length=320)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('compare_price', models.DecimalField(blank=True, decimal_places=2, help_text='Precio original antes del descuento', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('rating_count', models.PositiveIntegerField(default=0)),
                ('semantic_tags', models.JSONField(default=list, help_text='Etiquetas semánticas generadas por inferencia ontológica')),
                ('ontology_class', models.CharField(blank=True, db_index=True, help_text='URI completa de la clase OWL: http://www.smartstore.org/ontology#Smartphone', max_length=300)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='stores.store')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['store', 'is_active'], name='product_store_active_idx'), models.Index(fields=['price'], name='product_price_idx'), models.Index(fields=['rating'], name='product_rating_idx'), models.Index(fields=['store', 'price'], name='product_store_price_idx'), models.Index(fields=['ontology_class', 'is_active'], name='product_ontology_active_idx')],
                'unique_together': {('store', 'slug')},
            },
        ),
    ]
